name: Python package

on:
  push:
    branches: [ "release/dev", "release/live" ]

permissions:
  id-token: write
  contents: read
  
jobs:
  upload_source_files:
    runs-on: ubuntu-latest
    environment: ${{ github.ref == 'refs/heads/release/live' && 'live' || 'dev' }}
    steps:
      - uses: actions/checkout@v4

      - name: Set AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: ${{ secrets.CICD_ROLE_ARN }}
          aws-region: ap-northeast-2

      - name: Create source.zip
        run: |
          sudo apt-get update && sudo apt-get install -y zip
          zip -r source.zip . -x ".git/*"

      - name: Upload to S3
        run: |
          BUCKET_NAME=${{ vars.GIT_PROJECT_NAME }}
          aws s3 cp source.zip s3://codepipeline-mimir-cicd/${BUCKET_NAME}/source.zip
